[study]
name = "model"
description = "diplacements & pressure from porous media flow"
variable = "P"
num_trials = 100


[paths]
root = "C:/Users/cluster/constantinos/mytorch/studies/bio-surrogate"
raw = "{paths.root}/data/raw"
workdir = "{paths.root}/{study.name}"
cae = "{paths.root}/cae/"
ffnn = "{paths.root}/ffnn/"


features = "{paths.raw}/solutions/parameters.npy"
targets = "{paths.cae}/input/features.npy"

input = "{paths.ffnn}/input/"
output = "{paths.workdir}/output/"

figures = "{paths.workdir}/figures/"
checkpoints_ffnn = "{paths.ffnn}/checkpoints/"
checkpoints_cae = "{paths.cae}/checkpoints/"
logs = "{paths.workdir}/logs/"
predictions = "{paths.output}/predictions.npy"



