[tool.poetry]
name = "mytorch"
version = "0.1.0"
description = "custom modules and networks for pytorch"
authors = ["constatza <29166969+constatza@users.noreply.github.com>"]
readme = "README.md"
packages = [
    { include = "mytorch", from = "./src" },
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.0"
pydantic = "^2.7.4"
torch = "^2.3.1"
pathlib = "^1.0.1"


tomlkit = "^0.12.5"
[tool.poetry.group.test.dependencies]
pytest = "^8.2.2"



[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
    "src",
]
