name = "p-problem-1d-latent"
description = "pressures from porous media flow"
variable = "P"

[model]

networks = ["caes.LinearChannelDescentLatent1d"]
kernel-size = [7, 9]
num-layers = [4, 5]
latent-size = [3, 6]



[training]
batch-size = [32]
learning-rate = [1e-4]
num-epochs = 6000

[test]
model = "LinearChannelDescentLatent1d_2.pt"

[paths.input]
solutions = "./formatted_solutions.npy"
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\processed\\p-problem"
x-train = "./x_train.pt"
x-test = "./x_test.pt"
y-train = "./x_train.pt"
y-test = "./x_test.pt"
means = "./means.pt"
stds = "./stds.pt"
dataset = "./dataset.pt"
latent = "./latent.pt"

[paths.output]
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\output\\{name}\\"
img = "./img/"
models = "./models/"
parameters = "./parameters/"
figures = "./figures/"

[paths.raw]
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\raw\\"
dofs = "./dofs/Pdofs.txt"
data = "./solutions500/porousSolutions.npy"
