name = "u-problem"
description = "diplacements from porous media flow"
variable = "U"

[model]
networks = ["caes.CAE1dLinear2"]
num-layers = [4, 6]

[training]
batch-size = [32]
learning-rate = [1e-3, 1e-4]
num-epochs = 6000

[test]
model = "CAE1dLinear2_1.pt"

[paths.input]
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\processed\\{name}"
x-train = "./x_train.pt"
x-test = "./x_test.pt"
means = "./means.pt"
stds = "./stds.pt"

[paths.raw]
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\raw\\"
dofs = "./dofs/Udofs.txt"
data = "./solutions500/porousSolutions.npy"

[paths.output]
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\output\\{name}\\"
img = "./img/"
models = "./models/"
parameters = "./parameters/"
figures = "./figures/"
