[study]
name = "ffnn"
description = "diplacements & pressure from porous media flow"
variable = "P"
delete_old = true
num_trials = 100


[paths]
root = "C:/Users/cluster/constantinos/mytorch/studies/bio-surrogate"
raw = "C:/Users/cluster/constantinos/mytorch/studies/bio-surrogate/data/raw"
workdir = "C:/Users/cluster/constantinos/mytorch/studies/bio-surrogate/{study.name}"
cae = "{paths.root}/cae/"


features = "{paths.raw}/solutions/parameters.npy"
targets = "{paths.cae}/output/latent.npy"

input = "{paths.workdir}/input/"
output = "{paths.workdir}/output/"

figures = "{paths.workdir}/figures/"
checkpoints = "{paths.workdir}/checkpoints/"
logs = "{paths.workdir}/logs/"
predictions = "{paths.output}/predictions.npy"
metadata = "{paths.root}/cae/input/metadata.npz"



