[scenario]
name = "p-problem-ffnn"
source="p-problem-ffnn-train-test"
description = "feedforward neural network for the porous media problem"

[model]
networks = ['ffnns.ConstantHiddenSizeFFNN']
hidden-layers = [5, 10]
hidden-size = [100, 1000]


[training]
batch-size = [128]
learning-rate = [5e-6]
num-epochs = 16000

[test]
model = "ConstantHiddenSizeFFNN_0.pt"

[paths.input]
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\processed\\{source}"
x-train = "./x_train_scaled.pt"
x-test = "./x_test_scaled.pt"
y-train = "./y_train_scaled.pt"
y-test = "./y_test_scaled.pt"


[paths.output]
root = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\output\\{name}\\"
img = "./img/"
models = "./models/"
parameters = "./parameters/"
figures = "./figures/"
