[study]
name = "u-problem"
description = "diplacements from porous media flow"
variable = "U"
delete-old = true
logger = "progress"
num-trials = 3

[model]
name = "caes.LinearChannelDescentVAE"
#name = "caes.LinearChannelDescentLatent1d"
kernel-size = [7]
num-layers = [4]
latent-size = [3, 6, 9]
convolution-dims = 1

[training]
batch-size = [32]
learning-rate = [2e-4]
num-epochs = 300
optimizer = "Adam"
criterion = "MSELoss"

[test]

[paths.input]
root-dir = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\processed\\{study.name}"
x-train = "./x_train_scaled.npy"
x-test = "./x_test_scaled.npy"
y-train = "./x_train_scaled.npy"
y-test = "./x_test_scaled.npy"
means = "./means.npy"
stds = "./stds.npy"
dataset = "./dataset.npy"
latent = "./latent.npy"

[paths.raw]
root-dir = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\raw\\"
dofs = "./dofs/Udofs.txt"
data = "./solutions500/porousSolutions.npy"

[paths.output]
root-dir = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\output\\{study.name}\\"
img-dir = "./img/"
models-dir = "./models/"
parameters-dir = "./parameters/"
figures-dir = "./figures/"
logs-dir = "./logs/"
results-dir = "./results/"
