[study]
name = "u-problem-ffnn-train-test"
source = "u-problem"
description = "split the data into train and test sets"


[paths.input]
root-dir = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\processed\\{study.source}"
latent = "./latent_data_mean.npy"

[paths.raw]
root-dir = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\raw\\"
parameters = "./solutions500/parameters.npy"


[paths.output]
root-dir = "C:\\Users\\cluster\\constantinos\\mytorch\\data\\processed\\{study.name}\\"
x_train = "./x_train.npy"
x_test = "./x_test.npy"
y_train = "./y_train.npy"
y_test = "./y_test.npy"
x_train_scaled = "./x_train_scaled.npy"
x_test_scaled = "./x_test_scaled.npy"
y_train_scaled = "./y_train_scaled.npy"
y_test_scaled = "./y_test_scaled.npy"
