[study]
name = "u_problem_ffnn"
source = "u_problem_ffnn_train_test"
description = "feedforward neural network for the porous media problem"

[model]
name = ['ffnns.ConstantHiddenSizeFFNN']
hidden_layers = [1]
hidden_size = [200, ]
input_shape = [-1, 3]



[training]
batch_size = [128]
learning_rate = [1e-3, 1e-4]
num_epochs = 25000

[test]
model = "ConstantHiddenSizeFFNN_0.pt"

[paths]
input = "C:/Users/cluster/constantinos/mytorch/data/processed/{study.source}"
output = "C:/Users/cluster/constantinos/mytorch/data/output/{study.name}/"


x_train = "{paths.input}/parameters_train_scaled.npy"
x_test = "{paths.input}/parameters_test_scaled.npy"
y_train = "{paths.input}/y_train_scaled.npy"
y_test = "{paths.input}/y_test_scaled.npy"


img = "{paths.output}/img/"
models_dir = "{paths.output}/models/"
parameters = "{paths.output}/parameters/"
figures = "{paths.output}/figures/"
