[study]
name = "cae"
description = "diplacements & pressure from porous media flow"
variable = "U,P"
delete_old = true
num_trials = 100

[model]
name = "caes.LinearChannelDescentLatent1d"
kernel_size = [5]
num_layers = 4
latent_size = [2, 12, 1]
convolution_dims = 1
input_shape = [-1, 1731, 730]

[training]
batch_size = [32]
learning_rate = [1e-5, 1e-3]
num_epochs = 100
optimizer = "RAdam"


[paths]
dataroot = "M:/constantinos/data/bio/5-equations/"
workdir = "C:/Users/cluster/constantinos/mytorch/studies/bio-surrogate/{study.name}"

features = "{paths.input}/solutions.npy"

input = "{paths.dataroot}/input/"
output = "{paths.dataroot}/output/"
figures = "{paths.output}/figures/"
checkpoints = "{paths.output}/checkpoints/"
logs = "{paths.output}/logs/"
latent = "{paths.output}/latent.npy"
targets = "{paths.input}/volumes.csv"


predictions = "{paths.output}/predictions.npy"
parameters = "{paths.input}/parameters.npy"



