name: Testing

on: push

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pytest
        run: pip install pytest

      - name: Run Tests
        run: pytest ./tests/
